{
  try {
    return method.invoke(null,arguments);
  }
 catch (  IllegalAccessException exception) {
    throw new AssertionError(exception);
  }
catch (  InvocationTargetException exception) {
    final Throwable cause=exception.getTargetException();
    if (cause instanceof RuntimeException) {
      throw (RuntimeException)cause;
    }
    if (cause instanceof Error) {
      throw (Error)cause;
    }
    throw exception;
  }
}
